### ISSUE TITLE
canContinueScanning could be simplified

### ISSUE THREAD

**Issue by marcusklaas** [JordyMoos/JMTradingHouseSnapshot#1]
I have browsed through your code, and it looks very good! The comments make it very clear what's going on, even without lua experience. The readme is nice as well.

The only suggestion I have is an extremely trivial one: the logic in `canContinueScanning` could be simplified to `return TraidingHouse.isOpen and Scanner.isScanning`. This makes its behaviour a bit more evident in my view. We've talked about this in the past and I remember you weren't convinced 100% so feel free to ignore me (again!) :-P

**Comment by JordyMoos** [comment]
Yea you are right it is a bit too verbose. I commited your request :)

**Comment by marcusklaas** [comment]
Cool!

**Comment by JordyMoos** [comment]
Thanks @marcusklaas :)
